#!/bin/sh

item_name=$1
item_user="pipikun"
item_author="Xiaokun Peng"
item_email="xkpeng@jlsemi.com"

if [ -z "${item_name}" ]; then
    echo "Enter a project name."
    echo "such as 'create empty'"
    exit 0
fi

item_git="git@github.com:${item_user}/${item_name}.git"

# outpou project name
echo "Create project ..."
echo "--> name   : ${item_name}"
echo "--> author : ${item_author}"
echo "--> remote : ${item_git}"

# git config
git config --global user.name "${item_author}"
git config --global user.email "${item_email}"

# git setup
git init
# add readme
echo "# ${item_name}" >> README.md
# add gitignore
echo "build/" >> .gitignore

git add .
git commit -m 'first commit.'
git branch -M main

